import { Product } from "./product";

export const PRODUCTS: Product[] = [
  {
    productId: '1',
    userId: 'jin',
    productTitle: 'reiskocher',
    productPrice: 80,
    productImage: ['../assets/image/cuchen.jpeg','../assets/image/jacket.jpeg','../assets/image/bicycle.jpeg'],
    postDate: '24.10.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '2',
    userId: 'hyun',
    productTitle: 'bicycle',
    productPrice: 120,
    productImage: ['../assets/image/bicycle.jpeg'],
    postDate: '13.10.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '3',
    userId: 'min',
    productTitle: 'jacket',
    productPrice: 40,
    productImage: ['../assets/image/jacket.jpeg'],
    postDate: '8.10.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '4',
    userId: 'hyun',
    productTitle: 'shelf',
    productPrice: 33,
    productImage: ['../assets/image/shelf.jpeg'],
    postDate: '15.11.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '5',
    userId: 'hyun',
    productTitle: 'shelf',
    productPrice: 33,
    productImage: ['../assets/image/shelf.jpeg'],
    postDate: '19.10.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '6',
    userId: 'hyun',
    productTitle: '냉장고',
    productPrice: 120,
    productImage: ['../assets/image/refrigerator.jpeg'],
    postDate: '19.10.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '7',
    userId: 'min',
    productTitle: '전자레인지',
    productPrice: 25,
    productImage: ['../assets/image/microwave.jpeg'],
    postDate: '15.11.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '8',
    userId: 'hyun',
    productTitle: 'bicycle',
    productPrice: 120,
    productImage: ['../assets/image/bicycle.jpeg'],
    postDate: '30.10.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '1',
    userId: 'jin',
    productTitle: 'reiskocher',
    productPrice: 80,
    productImage: ['../assets/image/cuchen.jpeg','../assets/image/jacket.jpeg','../assets/image/bicycle.jpeg'],
    postDate: '24.10.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '2',
    userId: 'hyun',
    productTitle: 'bicycle',
    productPrice: 120,
    productImage: ['../assets/image/bicycle.jpeg'],
    postDate: '24.10.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '3',
    userId: 'min',
    productTitle: 'jacket',
    productPrice: 40,
    productImage: ['../assets/image/jacket.jpeg'],
    postDate: '8.10.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '4',
    userId: 'hyun',
    productTitle: 'shelf',
    productPrice: 33,
    productImage: ['../assets/image/shelf.jpeg'],
    postDate: '15.11.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '5',
    userId: 'hyun',
    productTitle: 'shelf',
    productPrice: 33,
    productImage: ['../assets/image/shelf.jpeg'],
    postDate: '19.10.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '6',
    userId: 'hyun',
    productTitle: '냉장고',
    productPrice: 120,
    productImage: ['../assets/image/refrigerator.jpeg'],
    postDate: '19.10.22',
  },
  {
    productId: '7',
    userId: 'min',
    productTitle: '전자레인지',
    productPrice: 25,
    productImage: ['../assets/image/microwave.jpeg'],
    postDate: '15.11.22',
  },]
