import { Product } from "./product";

export const PRODUCTS: Product[] = [
  {
    productId: '1',
    userId: 'Jin',
    productTitle: 'reiskocher',
    productPrice: 80,
    productCategory: 'electronics',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis tellus id interdum velit laoreet id. Tristique nulla aliquet enim tortor at auctor. Montes nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Sed blandit libero volutpat sed. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Semper feugiat nibh sed pulvinar. Morbi tincidunt ornare massa eget. ',
    productImage: ['../assets/images/cuchen.jpeg','../assets/images/jacket.jpeg','../assets/images/bicycle.jpeg'],
    contact: 'anonym@rwth-aachen.de',
    dealType: 'sell',
    postDate: '24.10.22',
  },
  {
    productId: '2',
    userId: 'Hyun',
    productTitle: 'bicycle',
    productPrice: 120,
    productCategory: 'electronics',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis tellus id interdum velit laoreet id. Tristique nulla aliquet enim tortor at auctor. Montes nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Sed blandit libero volutpat sed. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Semper feugiat nibh sed pulvinar. Morbi tincidunt ornare massa eget. ',
    productImage: ['../assets/images/bicycle.jpeg'],
    contact: 'anonym@rwth-aachen.de',
    dealType: 'sell',
    postDate: '24.10.22',
  },
  {
    productId: '3',
    userId: 'Jin',
    productTitle: 'Jacket',
    productPrice: 45,
    productCategory: 'clothing',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis tellus id interdum velit laoreet id. Tristique nulla aliquet enim tortor at auctor. Montes nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Sed blandit libero volutpat sed. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Semper feugiat nibh sed pulvinar. Morbi tincidunt ornare massa eget. ',
    productImage: ['../assets/images/jacket.jpeg'],
    contact: 'anonym@rwth-aachen.de',
    dealType: 'sell',
    postDate: '24.10.22',
  },
  {
    productId: '4',
    userId: 'hyun',
    productTitle: 'shelf',
    productPrice: 33,
    productCategory: 'electronics',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis tellus id interdum velit laoreet id. Tristique nulla aliquet enim tortor at auctor. Montes nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Sed blandit libero volutpat sed. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Semper feugiat nibh sed pulvinar. Morbi tincidunt ornare massa eget. ',
    productImage: ['../assets/images/shelf.jpeg'],
    dealType: 'sell',
    postDate: '15.11.22',
  },
  {
    productId: '5',
    userId: 'hyun',
    productTitle: 'shelf',
    productPrice: 33,
    productCategory: 'electronics',
    productDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis tellus id interdum velit laoreet id. Tristique nulla aliquet enim tortor at auctor. Montes nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Sed blandit libero volutpat sed. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Semper feugiat nibh sed pulvinar. Morbi tincidunt ornare massa eget. ',
    productImage: ['../assets/images/shelf.jpeg'],
    postDate: '19.10.22',
    dealType: 'sell',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '6',
    userId: 'hyun',
    productTitle: '냉장고',
    productPrice: 120,
    productImage: ['../assets/images/refrigerator.jpeg'],
    postDate: '19.10.22',
    contact: 'anonym@rwth-aachen.de',  },
  {
    productId: '7',
    userId: 'min',
    productTitle: '전자레인지',
    productPrice: 25,
    productImage: ['../assets/images/microwave.jpeg'],
    postDate: '15.11.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '8',
    userId: 'hyun',
    productTitle: 'bicycle',
    productPrice: 120,
    productImage: ['../assets/images/bicycle.jpeg'],
    postDate: '30.10.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '6',
    userId: 'hyun',
    productTitle: '냉장고',
    productPrice: 120,
    productImage: ['../assets/images/refrigerator.jpeg'],
    postDate: '19.10.22',
    contact: 'anonym@rwth-aachen.de',  },
  {
    productId: '7',
    userId: 'min',
    productTitle: '전자레인지',
    productPrice: 25,
    productImage: ['../assets/images/microwave.jpeg'],
    postDate: '15.11.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '8',
    userId: 'hyun',
    productTitle: 'bicycle',
    productPrice: 120,
    productImage: ['../assets/images/bicycle.jpeg'],
    postDate: '30.10.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '6',
    userId: 'hyun',
    productTitle: '냉장고',
    productPrice: 120,
    productImage: ['../assets/images/refrigerator.jpeg'],
    postDate: '19.10.22',
    contact: 'anonym@rwth-aachen.de',  },
  {
    productId: '7',
    userId: 'min',
    productTitle: '전자레인지',
    productPrice: 25,
    productImage: ['../assets/images/microwave.jpeg'],
    postDate: '15.11.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '8',
    userId: 'hyun',
    productTitle: 'bicycle',
    productPrice: 120,
    productImage: ['../assets/images/bicycle.jpeg'],
    postDate: '30.10.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '9',
    userId: 'hyun',
    productTitle: '냉장고',
    productPrice: 120,
    productImage: ['../assets/images/refrigerator.jpeg'],
    postDate: '19.10.22',
    contact: 'anonym@rwth-aachen.de',  },
  {
    productId: '10',
    userId: 'min',
    productTitle: '전자레인지',
    productPrice: 25,
    productImage: ['../assets/images/microwave.jpeg'],
    postDate: '15.11.22',
    contact: 'anonym@rwth-aachen.de',
  },
  {
    productId: '11',
    userId: 'hyun',
    productTitle: 'bicycle',
    productPrice: 120,
    productImage: ['../assets/images/bicycle.jpeg'],
    postDate: '30.10.22',
    contact: 'anonym@rwth-aachen.de',
  },
]
